version: '3.8'

services:
  app:
    container_name: car-manager-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=devuser
      - DB_PASSWORD=devpass
      - DB_NAME=devdb
    depends_on:
      - postgres
    networks:
      - dev-network

  postgres:
    image: postgres:15-alpine
    container_name: car-manager-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_DB=devdb
    ports:
      - "5432:5432"
    networks:
      - dev-network

volumes:
  go-modules:
  postgres-data:

networks:
  dev-network: